albums_app/urls.py
from django.urls import path

from . import views

app_name = 'albums_app'

urlpatterns = [
  path('', views.AlbumList.as_view(), name='album_list'),
  path('new/', views.BookCreate.as_view(), name='album_new'),
  path('edit/<int:pk>/', views.BookUpdate.as_view(), name='album_edit'),
  path('delete/<int:pk>/', views.BookDelete.as_view(), name='album_delete'),
  path('itunes/', views.itunes_renew, name='test'),
  path('stress/', views.stress_ng, name='stress'),
  path('async/', views.itunes_async, name='async')
  #path('renew/', views.ItunesUpdate.as_view(), name='album_renew'),
]

apps/urls.py
from django.urls import include, path
from django.contrib import admin

import theme.views

urlpatterns = [
    path('',  include('albums_app.urls')),
     # Enable built-in authentication views

    # Enable built-in admin interface
    path('admin/', admin.site.urls)
]

albums_app/models.py
from django.db import models
from django.urls import reverse

#kind, collectionName, trackName, collectionPrice, trackPrice, primaryGenreName, trackCount, trackNumber, releaseDate.
#album_name.collection_name, album_name.primaryGenreName, album_name.track_count, album_name.release_date, album_name.collection_id)
class Album(models.Model):
    collectionPrice = models.DecimalField(max_digits=9, decimal_places=2)
    primaryGenreName = models.CharField(max_length=200, default="Pop")
    trackCount = models.IntegerField(default=1)
    name = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    releaseDate = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('albums_app:album_edit', kwargs={'pk': self.pk})

    class Meta:
        ordering = ["releaseDate"]    

albums_app/views.py
import datetime
import time
import subprocess
from django.http import HttpResponse
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy
import itunespy, json, subprocess, os
from django.core.management import execute_from_command_line

from .models import Album

class AlbumList(ListView):
    model = Album
    fields = ['name', 'author']

class BookCreate(CreateView):
    model = Album
    fields = ['name', 'author', 'collectionPrice', 'primaryGenreName', 'trackCount', 'releaseDate']
    success_url = reverse_lazy('albums_app:album_list')

class BookUpdate(UpdateView):
    model = Album
    fields = ['name',  'author']
    success_url = reverse_lazy('albums_app:album_list')

class BookDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('albums_app:album_list')


def itunes_renew(request):
        artist = itunespy.search_artist('The Beatles')  # Returns a list
        albums = artist[0].get_albums()  # Get albums from the first result
        album_array = []
        id = 0
        for album in albums:
            time.sleep(1)
            album_name = album
            album = itunespy.lookup(album.collection_id)
            tracks = album[0].get_tracks()  # Get tracks from the first result
            album_dict = dict()
            if tracks == []:
                pass
            else:
                id = id + 1
                print("---------------------------------------")
                print("collectin name^^^^")
                # release_date = datetime.strptime(album_name.release_date, "%Y-%m-%d") 
                print(album_name.collection_name, album_name.primaryGenreName, album_name.track_count,
                      album_name.release_date, album_name.collection_id)
                album_dict = {"model": "albums_app.Album",
                              "pk": id,
                              "fields": {
                                  "collectionPrice": album_name.collection_price,
                                  "primaryGenreName": album_name.primaryGenreName,
                                  "trackCount": album_name.track_count,
                                  "name": album_name.collection_name,
                                  "author": album_name.artist_name,
                                  "releaseDate": datetime.datetime.strptime(album_name.release_date,"%Y-%m-%dT%H:%M:%SZ").strftime("%Y-%m-%d")
                                  
                              }
                              }
                album_array.append(album_dict)
                for track in tracks:
                    print(str(
                        track.track_number) + " " + track.kind + " " + track.collection_name + ': ' + track.track_name + " price " + str(
                        track.track_price) + "time: " + str(track.get_track_time_minutes()))
                print('Total playing time: ' + str(album[0].get_album_time()))

        print(album_array)
        
        album_array = json.dumps(album_array, separators=(',', ':'))
         
        album_array = str(album_array)
        
        f = open('/usr/src/app/albums_app/fixtures/data.json', 'w')
        f.write(album_array)
        f.close()
        return HttpResponse('OK', status=200)

def itunes_async(request):
    execute_from_command_line(['manage.py', "loaddata", '/usr/src/app/albums_app/fixtures/data.json'])
    return HttpResponse('OK', status=200)

def stress_ng(request):
    print('stress test')
    subprocess.run(["stress-ng", "--cpu", "4", "--cpu-method", "matrixprod", "--metrics", "--timeout", "60"])
    return HttpResponse('OK', status=200)

albums_app/templates/albums_app/album_confirm_delete.html
{% extends "base.html" %}

{% block content %}


<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?<br>
    <input type="submit" value="Delete" />
</form>
<div class="text-center">
    <a class="btn btn-primary" role="button" href="{% url 'albums_app:album_list' %}">Cancel</a>
  </div>



{% endblock %}

albums_app/templates/albums_app/album_form.html
{% extends "base.html" %}

{% block content %}

<form class="row gy-2 gx-3  align-items-center" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
<div class="text-center">
    <a class="btn btn-primary" role="button" href="{% url 'albums_app:album_list' %}">Cancel</a>
</div>

{% endblock %}

albums_app/templates/albums_app/album_list.html
{% extends "base.html" %}

{% block content %}

<h2 class="list-title">Album List</h2>

<table class="table table-dark table-striped table-hover">
    <thead>
        <tr>
          <th scope="col">Album Name</th>
          <th scope="col">Album Author</th>
          <th scope="col">Album Price</th>
          <th scope="col">Tracks Count</th>
          <th scope="col">Release Date</th>
          <th scope="col">Edit</th>
          <th scope="col">Delete</th>
        </tr>
      </thead>
<tbody>
    {% for album in object_list %}
<tr>
    <td>{{ album.name }} </td>
    <td>{{ album.author }} </td>
    <td>{{ album.collectionPrice}} </td>
    <td>{{album.trackCount}} </td> 
    <td>{{album.releaseDate}}</td>


   <td><a class="btn btn-primary" href="{% url 'albums_app:album_edit' album.id %}">edit </a></td>
   <td><a class="btn btn-danger" href="{% url 'albums_app:album_delete' album.id %}">delete</a> </td>

    {% endfor %}
</tr>
</tbody>
</table>
</ul>

<div class="btn-container">
  <a class="btn btn-secondary" role="button" href="{% url 'albums_app:album_new' %}">New</a>
  <a class="btn btn-secondary" role="button" href="{% url 'albums_app:test' %}">Renew data</a>
  <a class="btn btn-secondary" role="button" href="{% url 'albums_app:async' %}">Download data</a>
  <a class="btn btn-secondary" role="button" href="{% url 'albums_app:stress' %}">Scaling test</a>
</div>






{% endblock %}